name: ReqRes API Automation

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select branch"
        required: true
        type: choice
        options:
          - main
          - master
          - develop
          - release


jobs:

  api-test:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}


    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven


    - name: Run API Automation
      run: |
        mvn clean test


    - name: Generate Allure Report
      if: always()
      run: |
        mvn allure:report


    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Allure-API-Report
        path: target/site/allure-maven-plugin
